### ISSUE TITLE
Use nicknames instead of usernames for Starboard entries

### ISSUE THREAD

**Issue by AstreaTSS** [TheNoob27/starboard-issues#8]
Long time no see, huh?

Currently, when Starboard puts a message in its starboard channel, it uses the person's username (IE Sonic49#7171). This is okay in some circumstances, and might even be ideal for some, but many people have nicknames on servers that are drastically different than their usernames (IE Sonic49#7171 having the nickname of "Stupid Pineapple" on a server), and so seeing only the username may cause confusion.

I would suggest using the nickname over the username system. If you really still wanted the username in it somehow, you could use a [nickname] ([username]) format to keep both and have the benefits of both worlds, or you could make it a setting to toggle on.

**Comment by TheNoob27** [comment]
A while ago there was a poll about this, resulting in a tie (9-9) so I made a second poll about it and it was 5-9, so I then made the change.

But I decided to revert it back because someone in the support server changed their nickname and avatar to MY nickname and avatar, and got a message on the starboard.
I feel like using their nicknames could cause users to be tricking people by starring messages while impersonating server admins, making people think the actual admin said that, or something along the lines of that, so I reverted it. 

But I could do the little bracket thing you suggested, like `helo (TheNoob27#6815)`, I'll think about it

**Comment by AstreaTSS** [comment]
No doubt people could use it to impersonate, but honestly people could just change their usernames too, and not many people would pay attention to the discriminator. Or maybe that's just my way of thinking.

Either way, I feel like the bracket solution would be the best. Personally, I've done it for my own (personal) bot, and it seems to work well.

**Comment by Luke-6723** [comment]
Could always add this as an Opt-in configurable setting. With a feature than allows server mods to say whether not to to put the authors actual name in perenthesis

**Comment by TheNoob27** [comment]
done 💖
